CREATE DATABASE IF NOT EXISTS tracktruck;
USE tracktruck;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  fullname VARCHAR(120) NOT NULL,
  email VARCHAR(180) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  contact VARCHAR(20) NOT NULL,
  role ENUM('driver', 'owner', 'admin') NOT NULL DEFAULT 'driver',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS trips (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  driver_id INT UNSIGNED NOT NULL,
  vehicle ENUM('Truck1', 'Truck2') NOT NULL,
  trip_date DATE NOT NULL,
  from_location VARCHAR(255) NULL,
  to_location VARCHAR(255) NULL,
  deposit DECIMAL(10, 2) NOT NULL DEFAULT 0,
  cost DECIMAL(10, 2) NOT NULL DEFAULT 0,
  comments TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX trips_driver_id_idx (driver_id),
  CONSTRAINT trips_driver_id_fk FOREIGN KEY (driver_id)
    REFERENCES users(id)
    ON DELETE CASCADE
);

